### ISSUE TITLE
Ensure that witness costs are charged per-tx and not per-block

### ISSUE THREAD

**Issue by gballet** [ethereum/go-verkle#137]
The EIP definitions have changed, and the witness costs have to be charged per-transaction. We need to ensure that this is what the code does, because the old behavior was to charge said costs per-block.

**Comment by jwasinger** [comment]
In https://github.com/gballet/go-ethereum/pull/37, I'm fairly sure this is the case.  The `AccessWitness` used is per-`TxContext` (which as the name implies, only exists for the lifetime of a transaction).

**Comment by gballet** [comment]
Long fixed. Closing.
