### ISSUE TITLE
use slice instead of pointer to [32]byte array in SuffixDiff

### ISSUE THREAD

**Issue by gballet** [ethereum/go-verkle#388]
It is possible to use a slice and check that the value casts to the right length by using a marshaling structure.

**Comment by jsign** [comment]
Related to SSZ discussions.

**Comment by gballet** [comment]
It turns out that, indeed, empty slices are encoded as `null` and so we could use `[]byte` to do this. This would requite us to double-check that the decoded value is always 32 bytes however, so we need to add more code after deserialization.

The issue comes with SSZ encoding, which Péter wants to push in the engine api. This should be implemented with optionals, but there is one issue: there is no support for them in most SSZ libraries (except of course ssz.zig, the best SSZ library out there :heart: ) so I guess the spec will change in order to either support stable containers or simply use something like #447. So there's no point in keeping this issue open, the problem will fix itself.
